# -*- coding: utf-8 -*-
"""VietOCR.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1POeMtYpc_CYrSMgZGouHuHD-YED6xtQH
"""

import matplotlib.pyplot as plt
from PIL import Image
from vietocr.tool.predictor import Predictor
from vietocr.tool.config import Cfg
import cv2
import numpy as np

config = Cfg.load_config_from_name('vgg_seq2seq')

# config['weights'] = './weights/transformerocr.pth'
config['weights'] = 'https://drive.google.com/uc?id=1MDooHUSR1QbZrKr0td_2Hp84L7yAJqFn'
#config['weights'] = "/content/drive/MyDrive/MCOCR/weights/transformerocr.pth"
config['cnn']['pretrained']=False
config['device'] = 'cpu'
config['predictor']['beamsearch']=False

detector = Predictor(config)

def vietocr_predict_image(image, gpu):

  img = Image.fromarray(np.uint8(image))
  s = detector.predict(img)
  return s